### ISSUE TITLE
moldova: High error rate (2024-04)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#1083]
From #1056 

> 35k missing contracting processes is a lot

Currently seeing a lot of these (from my own computer):

```json
{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at connResetException (internal/errors.js:609:14)\n    at TLSSocket.socketOnEnd (_http_client.js:453:23)\n    at TLSSocket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1221:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"https://mtender.gov.md/search/complaints?NrProcedurii=ocds-b3wdp1-MD-1713426631402&page=1","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.21.1"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"ECONNRESET"}
```

Not a single item was yielded during the 3.5 hour crawl (before being cancelled)

https://collect.data.open-contracting.org/logs/kingfisher/moldova/0dfbccde03d911efaf9aa8a159689b50.log

**Comment by jpmckinney** [comment]
Duplicate #1084

**Comment by jpmckinney** [comment]
Already frozen in registry (not sure when, but no jobs since Jan 2024)

**Comment by yolile** [comment]
>  Already frozen in registry (not sure when, but no jobs since Jan 2024)

Since April 2024
https://github.com/open-contracting/kingfisher-collect/issues/1084#issuecomment-2079852677

**Comment by yolile** [comment]
Note that https://public.mtender.gov.md/tenders/{ocid} response without errors, but from the code notes, we know that this service publishes contracting processes under multiple OCIDs. So I guess it is fine to not use that endpoint and therefore keep the spider deleted

**Comment by jpmckinney** [comment]
Yes, I think so. mtender.gov.md is basically not OCDS compliant, and I don't think we want to take responsibility for fixing its implementation (if that's possible).

Copying the code comments here for easy reference:

> https://public.mtender.gov.md offers three endpoints: /tenders/, /tenders/plan/ and /budgets/. However, this
> service publishes contracting processes under multiple OCIDs.
> 
> The http://public.eprocurement.systems/ocds/ service instead publishes contracting processes under one OCID.
> However, it has no endpoint to list OCIDs.
> 
> As such, we retrieve OCIDs from the first, and data from the second.
> 
> Note: The OCIDs from the /budgets/ endpoint have no corresponding data in the second service. The OCIDs from
> the /tenders/plan/ endpoint are the same as from the /tenders/ endpoint.
