### ISSUE TITLE
`moldova`: erros for all ocids (2024-04)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1084]
All requests response with: (e.g. http://public.eprocurement.systems/ocds/tenders/ocds-b3wdp1-MD-1539869760479)

```
{
  "message": "socket hang up",
  "name": "Error",
  "stack": "Error: socket hang up\n    at connResetException (internal/errors.js:609:14)\n    at TLSSocket.socketOnEnd (_http_client.js:453:23)\n    at TLSSocket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1221:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "config": {
    "url": "https://mtender.gov.md/search/complaints?NrProcedurii=ocds-b3wdp1-MD-1539869760479&page=1",
    "method": "get",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.21.1"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1
  },
  "code": "ECONNRESET"
}
```

**Comment by yolile** [comment]
Frozen in the registry

**Comment by yolile** [comment]
closing in favor of #1083
