### ISSUE TITLE
moldova: Occasional error response with HTTP 200 code

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#702]
These two URLs respond now, but they had the following responses.

@paulboroday Are you aware of this issue?

https://public.mtender.gov.md/tenders/ocds-b3wdp1-MD-1602163426198

`cat /home/ocdskfs/scrapyd/data/moldova/20210413_163855/tenders-ocds-b3wdp1-MD-1602163426198.json`

```json
{"message":"connect EHOSTUNREACH 185.108.182.236:443","name":"Error","stack":"Error: connect EHOSTUNREACH 185.108.182.236:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","config":{"url":"https://public.mtender.gov.md/tenders/ocds-b3wdp1-MD-1602163426198","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.21.1"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"EHOSTUNREACH"}
```

https://public.mtender.gov.md/tenders/ocds-b3wdp1-MD-1603913785143

`cat /home/ocdskfs/scrapyd/data/moldova/20210413_163855/tenders-ocds-b3wdp1-MD-1603913785143.json`

```json
{"message":"connect EHOSTUNREACH 185.108.182.236:443","name":"Error","stack":"Error: connect EHOSTUNREACH 185.108.182.236:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","config":{"url":"https://public.mtender.gov.md/tenders/ocds-b3wdp1-MD-1603913785143","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.21.1"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"EHOSTUNREACH"}
```

**Comment by yolile** [comment]
See https://github.com/open-contracting/kingfisher-collect/blob/98896754d3bf27479842009cc53164f850f0ccc7/kingfisher_scrapy/spiders/chile_base.py#L52 for an example of how to handle this kind of issue
