### ISSUE TITLE
France: JSON file is truncated

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/kingfisher-collect#730]
No data downloaded for France

```
2021-06-09 11:40:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20210609-052225/decp.ocds.json> (referer: https://www.data.gouv.fr/api/1/datasets/donnees-essentielles-de-la-commande-publique-fichiers-consolides/)
2021-06-09 11:41:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20210609-052225/decp.ocds.json> (referer: https://www.data.gouv.fr/api/1/datasets/donnees-essentielles-de-la-commande-publique-fichiers-consolides/)
Traceback (most recent call last):
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/home/datlab/kingfisher-collect/kingfisher_scrapy/middlewares.py", line 271, in process_spider_output
    for item in result:
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/home/datlab/kingfisher-collect/kingfisher_scrapy/middlewares.py", line 230, in process_spider_output
    package = self._get_package_metadata(item['data']['package'], 'releases', item['data_type'])
  File "/home/datlab/kingfisher-collect/kingfisher_scrapy/middlewares.py", line 260, in _get_package_metadata
    for item in util.items(ijson.parse(data), '', skip_key=skip_key):
  File "/home/datlab/ENV_KC/lib/python3.8/site-packages/ijson/utils.py", line 53, in coros2gen
    for value in source:
ijson.common.IncompleteJSONError: parse error: premature EOF
                     (right here) ------^
2021-06-09 11:41:08 [scrapy.core.engine] INFO: Closing spider (finished)
2021-06-09 11:41:08 [france] DEBUG: Sent sync request to kingfisher process url http://localhost:8000/api/v1/close_collection with data {'collection_id': 211, 'reason': 'finished', 'stats': {'log_count/INFO': 19, 'log_count/WARNING': 1, 'kingfisher_process_items_sent_post': 0, 'kingfisher_process_items_failed_post': 0, 'kingfisher_process_items_sent_rabbit': 0, 'kingfisher_process_items_failed_rabbit': 0, 'log_count/DEBUG': 155, 'start_time': '2021-06-09 09:40:32.972738', 'memusage/startup': 79667200, 'memusage/max': 79667200, 'scheduler/enqueued/memory': 2, 'scheduler/enqueued': 2, 'scheduler/dequeued/memory': 2, 'scheduler/dequeued': 2, 'downloader/request_count': 2, 'downloader/request_method_count/GET': 2, 'downloader/request_bytes': 772, 'downloader/response_count': 2, 'downloader/response_status_count/200': 2, 'downloader/response_bytes': 27822034, 'response_received_count': 2, 'request_depth_max': 1, 'log_count/ERROR': 1, 'spider_exceptions/IncompleteJSONError': 1, 'elapsed_time_seconds': 36.000167, 'finish_time': '2021-06-09 09:41:08.972905', 'finish_reason': 'finished'}}
2021-06-09 11:41:08 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): localhost:8000
2021-06-09 11:41:09 [urllib3.connectionpool] DEBUG: http://localhost:8000 "POST /api/v1/close_collection HTTP/1.1" 200 17
2021-06-09 11:41:09 [france] INFO: Closed collection in Kingfisher process with id 211
2021-06-09 11:41:09 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 772,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 27822034,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 36.000167,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 6, 9, 9, 41, 8, 972905),
 'kingfisher_process_items_failed_post': 0,
 'kingfisher_process_items_failed_rabbit': 0,
 'kingfisher_process_items_sent_post': 0,
 'kingfisher_process_items_sent_rabbit': 0,
 'log_count/DEBUG': 158,
 'log_count/ERROR': 1,
 'log_count/INFO': 20,
 'log_count/WARNING': 1,
 'memusage/max': 79667200,
 'memusage/startup': 79667200,
 'request_depth_max': 1,
 'response_received_count': 2,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/IncompleteJSONError': 1,
 'start_time': datetime.datetime(2021, 6, 9, 9, 40, 32, 972738)}
2021-06-09 11:41:09 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by yolile** [comment]
CRM-5227

**Comment by jpmckinney** [comment]
To reproduce:

```
curl https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20210611-052223/decp.ocds.json | tail -c 100
```

Last 100 characters are:

```
21","legalName":"Etablissement public territorial Plaine Commune "}},{"name":"SOUFFLET VIGNE","id":"
```

**Comment by yolile** [comment]
related GitHub issue: https://github.com/139bercy/decp-rama/issues/76

**Comment by yolile** [comment]
@hrubyjan they fixed the issue and this is working again

**Comment by jpmckinney** [comment]
France is broken again with truncated JSON: https://static.data.gouv.fr/resources/donnees-essentielles-de-la-commande-publique-fichiers-consolides/20211221-044754/decp.ocds.json

**Comment by yolile** [comment]
And now the JSON is not truncated anymore again, see the Kingfisher Collect logs [here](https://collect.kingfisher.open-contracting.org/logs/kingfisher/france/3ae2347cb5fc11ec88920c9d92c523cb.log)

**Comment by jpmckinney** [comment]
🎉  @yolile Can you enable it in the registry, etc.?

**Comment by yolile** [comment]
Yes, I will enable and disable all the publishers accordingly when I finalize the MEL 1 review 🙂
